# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse/core/src/main/protobuf/EdgeData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='warehouse/core/src/main/protobuf/EdgeData.proto',
  package='datawave.edge.protobuf',
  syntax='proto2',
  serialized_options=_b('\n\026datawave.edge.protobufH\001'),
  serialized_pb=_b('\n/warehouse/core/src/main/protobuf/EdgeData.proto\x12\x16\x64\x61tawave.edge.protobuf\"\xb9\x02\n\tEdgeValue\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x12\x11\n\x05hours\x18\x02 \x03(\x03\x42\x02\x10\x01\x12\x14\n\x08\x64uration\x18\x03 \x03(\x03\x42\x02\x10\x01\x12\x13\n\x0bhourBitmask\x18\x04 \x01(\x05\x12\x13\n\x0bsourceValue\x18\x05 \x01(\t\x12\x11\n\tsinkValue\x18\x06 \x01(\t\x12\x10\n\x08loadDate\x18\x07 \x01(\t\x12\x13\n\x0b\x62\x61\x64\x41\x63tivity\x18\x08 \x01(\x08\x12\x34\n\x04uuid\x18\t \x01(\x0b\x32&.datawave.edge.protobuf.EdgeValue.UUID\x12\x13\n\x0buuid_string\x18\n \x01(\t\x1a\x45\n\x04UUID\x12\x1e\n\x16least_significant_bits\x18\x01 \x02(\x12\x12\x1d\n\x15most_significant_bits\x18\x02 \x02(\x12\x42\x1a\n\x16\x64\x61tawave.edge.protobufH\x01')
)




_EDGEVALUE_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='datawave.edge.protobuf.EdgeValue.UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='least_significant_bits', full_name='datawave.edge.protobuf.EdgeValue.UUID.least_significant_bits', index=0,
      number=1, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='most_significant_bits', full_name='datawave.edge.protobuf.EdgeValue.UUID.most_significant_bits', index=1,
      number=2, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=389,
)

_EDGEVALUE = _descriptor.Descriptor(
  name='EdgeValue',
  full_name='datawave.edge.protobuf.EdgeValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='datawave.edge.protobuf.EdgeValue.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hours', full_name='datawave.edge.protobuf.EdgeValue.hours', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='datawave.edge.protobuf.EdgeValue.duration', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hourBitmask', full_name='datawave.edge.protobuf.EdgeValue.hourBitmask', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sourceValue', full_name='datawave.edge.protobuf.EdgeValue.sourceValue', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sinkValue', full_name='datawave.edge.protobuf.EdgeValue.sinkValue', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loadDate', full_name='datawave.edge.protobuf.EdgeValue.loadDate', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='badActivity', full_name='datawave.edge.protobuf.EdgeValue.badActivity', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='datawave.edge.protobuf.EdgeValue.uuid', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid_string', full_name='datawave.edge.protobuf.EdgeValue.uuid_string', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EDGEVALUE_UUID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=389,
)

_EDGEVALUE_UUID.containing_type = _EDGEVALUE
_EDGEVALUE.fields_by_name['uuid'].message_type = _EDGEVALUE_UUID
DESCRIPTOR.message_types_by_name['EdgeValue'] = _EDGEVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EdgeValue = _reflection.GeneratedProtocolMessageType('EdgeValue', (_message.Message,), {

  'UUID' : _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), {
    'DESCRIPTOR' : _EDGEVALUE_UUID,
    '__module__' : 'warehouse.core.src.main.protobuf.EdgeData_pb2'
    # @@protoc_insertion_point(class_scope:datawave.edge.protobuf.EdgeValue.UUID)
    })
  ,
  'DESCRIPTOR' : _EDGEVALUE,
  '__module__' : 'warehouse.core.src.main.protobuf.EdgeData_pb2'
  # @@protoc_insertion_point(class_scope:datawave.edge.protobuf.EdgeValue)
  })
_sym_db.RegisterMessage(EdgeValue)
_sym_db.RegisterMessage(EdgeValue.UUID)


DESCRIPTOR._options = None
_EDGEVALUE.fields_by_name['hours']._options = None
_EDGEVALUE.fields_by_name['duration']._options = None
# @@protoc_insertion_point(module_scope)
