# Generated by Django 2.2.10 on 2021-04-14 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_accumulocluster_edgequery_fileupload_ingestconfiguration_result_scanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatawaveWebservers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('cert_file', models.CharField(max_length=1024)),
                ('key_file', models.CharField(max_length=255)),
                ('key_password', models.CharField(max_length=255)),
                ('ca_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='cf',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AlterField(
            model_name='result',
            name='cq',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AlterField(
            model_name='result',
            name='row',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AlterField(
            model_name='result',
            name='value',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
