# Generated by Django 2.2.10 on 2021-04-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20210414_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawavewebservers',
            name='ca_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
